/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bloodsugar;

import java.util.HashMap;
import java.util.Optional;

public class App {

    private static class FoodDB {
        private HashMap<String, Double> foodDB = new HashMap<>();

        public void insertFood(String name, double bloodSugarLevel) {
            foodDB.put(name, bloodSugarLevel);
        }

        public Optional<Double> getBloodSugarLevel(String food) {
            return Optional.ofNullable(foodDB.get(food));
        }

        @Override 
        public String toString() {
            String output = "";

            for (String food : foodDB.keySet()) {
                output += food + " -> " + foodDB.get(food) + "\n";
            }

            return output;
        }
    }

    public static void main(String[] args) {
        FoodDB db = new FoodDB();
        db.insertFood("apple", 10);
        db.insertFood("banana", 20); 
        db.insertFood("orange", 30); 

        System.out.println(db);
    }
}
