/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mascots;

import java.util.HashMap;
import java.util.ArrayList;

public class App {

    private static class Suggestion {
        public final String name;
        public final String description;

        public Suggestion(String name, String description) {
            this.name = name;
            this.description = description;
        }
    }

    private static class SuggestionBox {
        private final HashMap<String, ArrayList<String>> suggestions = new HashMap<>();

        public void addSuggestion(Suggestion suggestion) {
            if (!suggestions.containsKey(suggestion.name)) {
                suggestions.put(suggestion.name, new ArrayList<>());
            }

            suggestions.get(suggestion.name).add(suggestion.description);
        }

        @Override 
        public String toString() {
            String output = "";

            for (String name : suggestions.keySet()) {
                output += name + "\n";

                for (String description : suggestions.get(name)) {
                    output += "  - " + description + "\n";
                }
            }

            return output;
        }
    }

    public static void main(String[] args) {
        SuggestionBox box = new SuggestionBox();

        box.addSuggestion(new Suggestion("Haskell", "It looks really cool"));
        box.addSuggestion(new Suggestion("Haskell", "It's a functional programming language"));
        box.addSuggestion(new Suggestion("Haskell", "It's a statically typed language")); 
        box.addSuggestion(new Suggestion("Java", "I'm unenlightened"));
        box.addSuggestion(new Suggestion("Java", "I like to type a lot"));
        box.addSuggestion(new Suggestion("Javascript", "I like pain"));

        System.out.println("Suggestions:");
        System.out.println(box);
    }
}
