/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package happyvet;

import java.util.Optional;
import java.util.Queue;
import java.util.LinkedList;

public class App {
    private static enum VisitType { REGULAR, EMERGENCY }

    private static class Appointment {
        public final String name;
        public final VisitType visitType; 
        public final String description;

        public Appointment(String name, VisitType visitType, String description) {
            this.name = name;
            this.visitType = visitType;
            this.description = description;
        }

        @Override 
        public String toString() {
            return String.format("Appointment(%s, %s, %s)", name, visitType, description);
        }
    }

    private static class Clinic {
        private Queue<Appointment> checkups = new LinkedList<>();
        private Queue<Appointment> emergencies = new LinkedList<>();

        public void addAppointment(Appointment appointment) {
            switch (appointment.visitType) {
                case REGULAR: checkups.add(appointment); break;
                case EMERGENCY: emergencies.add(appointment); break;
            }
        }

        public Optional<Appointment> getNextAppointment() {
            if (!emergencies.isEmpty()) {
                return Optional.of(emergencies.remove());
            } else if (!checkups.isEmpty()) {
                return Optional.of(checkups.remove());
            }

            return Optional.empty();
        }
    }

    public static void main(String[] args) {
        Clinic clinic = new Clinic();

        clinic.addAppointment(new Appointment("Alice", VisitType.REGULAR, "Annual checkup"));
        clinic.addAppointment(new Appointment("Bob", VisitType.EMERGENCY, "Broken leg"));
        clinic.addAppointment(new Appointment("Charlie", VisitType.REGULAR, "Vaccination"));

        Optional<Appointment> first = clinic.getNextAppointment();
        Optional<Appointment> second = clinic.getNextAppointment(); 
        Optional<Appointment> third = clinic.getNextAppointment();
        Optional<Appointment> fourth = clinic.getNextAppointment();

        System.out.println(first);
        System.out.println(second);
        System.out.println(third);
        System.out.println(fourth);
    }
}
