/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ratfeeding;

import java.util.ArrayList;

public class App {

    private static enum RatType { SICK, HEALTHY }

    private static class Rat {
        public final String name;
        public final RatType health;

        public Rat(String name, RatType health) {
            this.name = name;
            this.health = health;
        }

        @Override 
        public String toString() {
            return String.format("(Rat %s, %s)", name, health);
        }
    }

    private static class RatFeeder {
        private ArrayList<Rat> sick = new ArrayList<>();
        private ArrayList<Rat> healthy = new ArrayList<>();

        private int sickOffset = 0; // index at which to start feeding sick rats
        private int healthyOffset = 0; // index at which to start feeding healty rats

        public void addRat(Rat rat) {
            switch (rat.health) {
                case HEALTHY: healthy.add(rat); break; 
                case SICK: sick.add(rat); break;
            }
        }

        public void feed() {
            for (int i = 0; i < sick.size(); i++) {
                int index = (i + sickOffset) % sick.size();
                System.out.println(String.format("Feeding %s", sick.get(index)));
            }

            for (int i = 0; i < healthy.size(); i++) {
                int index = (i + healthyOffset) % healthy.size();
                System.out.println(String.format("Feeding %s", healthy.get(index)));
            }

            ++sickOffset;
            ++healthyOffset;
        }
    }

    public static void main(String[] args) {
        RatFeeder feeder = new RatFeeder();

        feeder.addRat(new Rat("Rat 1", RatType.SICK));
        feeder.addRat(new Rat("Rat 2", RatType.SICK));
        feeder.addRat(new Rat("Rat 3", RatType.HEALTHY));
        feeder.addRat(new Rat("Rat 4", RatType.HEALTHY));
        feeder.addRat(new Rat("Rat 5", RatType.HEALTHY));

        for (int i = 0; i < 3; i++) {
            feeder.feed();
            System.out.println("----------------");
        }
    }
}
